### ISSUE TITLE
Is it possible to substitute node_xslt with node-libxslt?

### ISSUE THREAD

**Issue by kildem** [albanm/node-libxslt#8] opened 2015-02-19 13:01 UTC
I'm trying to substitute node_xslt (which doesn't compile in node v0.12)  with node-libxslt in this module: https://github.com/jaydata/jaydata/blob/development/JaySvcUtil/JaySvcUtil.js line: 278.

this is what I've done:

            var libxslt = require('libxslt');
            var paramObj = {
                'SerivceUri':  "'" + cnf.SerivceUri + "'",
                'EntityBaseClass': "'" + cnf.EntityBaseClass + "'",
                'ContextBaseClass': "'" + cnf.ContextBaseClass + "'",
                'AutoCreateContext': "'" + cnf.AutoCreateContext + "'",
                'ContextInstanceName': "'" + cnf.ContextInstanceName + "'",
                'EntitySetBaseClass': "'" + cnf.EntitySetBaseClass + "'",
                'CollectionBaseClass':  + cnf.CollectionBaseClass + "'",
                'DefaultNamespace': "'" + cnf.DefaultNamespace + "'",
                'MaxDataserviceVersion': "'" + (versionInfo.maxVersion || '3.0') + "'",
                'AllowedTypesList': "'" + cnf.typeFilter + "'",
                'GenerateNavigationProperties': "'" + cnf.navigation + "'"
            };
            
            var stylesheetDoc = libxslt.libxmljs.parseXml(transformXslt);
            var stylesheet = libxslt.parse(stylesheetDoc);
            var result = stylesheet.apply(metadata,paramObj);
            return result;

but it doesn't work ... what's missing?

**Comment by albanm** [comment] 2015-02-19 14:47
Hello,

First, your paramObj object is too complicated. There is not need to add some quotes around each value. You should try without.

Second you don't need to use libxmljs.parseXml before using parse. You can simply pass a string to libxslt.parse. This is not an error though, just something not required.

Other than that I don't know, first try to remove your quotes. If it still doesn't work tell me more about the behavior, is there an error ? A trace in the console ? An incomplete result ?

**Comment by kildem** [comment] 2015-02-19 15:31
if I do: 


            var libxslt = require('libxslt');
            var paramObj = {
                'SerivceUri':  cnf.SerivceUri,
                'EntityBaseClass': cnf.EntityBaseClass,
                'ContextBaseClass': cnf.ContextBaseClass,
                'AutoCreateContext': cnf.AutoCreateContext ,
                'ContextInstanceName': cnf.ContextInstanceName ,
                'EntitySetBaseClass':  cnf.EntitySetBaseClass,
                'CollectionBaseClass':  cnf.CollectionBaseClass ,
                'DefaultNamespace':  cnf.DefaultNamespace ,
                'MaxDataserviceVersion':  (versionInfo.maxVersion || '3.0') ,
                'AllowedTypesList':  cnf.typeFilter ,
                'GenerateNavigationProperties':  cnf.navigation 
            };
            var stylesheet = libxslt.parse(transformXslt);
            var result = stylesheet.apply(metadata, paramObj);
           console.log(result);
           return result;

I get:
console.log(result) =


    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\n\n/*////////////////////////////////
    //////////////////////////////////////////////////////\n////// Autogenerated by Jay
    SvcUtil.exe http://JayData.org for more info        /////////\n//////              
               oData V2                                    /////////\n/////////////
    /////////////////////////////////////////////////////////////////////////*/\n(funct
    ion(global, $data, undefined) {\n\n
    .....
 
and the error I get is:

     { [Unexpected model: SyntaxError]
     name: 'Unexpected model',
     message: 'SyntaxError',
     data: 
      [ [SyntaxError: Unexpected token <],
        '<?xml version="1.0" encoding="UTF-8"?>\n\n\n/*
        .....

if I use node_xslt with node v<=10 (with node >= 11 node_xslt doesn't work)

console.log(result)=

    "\n\n/*/////////////////////////////////////////////////////////////////////////
    /////////////\n////// Autogenerated by JaySvcUtil.exe http://JayData.org for mor
    e info        /////////\n//////                             oData V2            
                        /////////\n/////////////////////////////////////////////
    /////////////////////////////////////////*/\n(function(global, $data, undefined)
     {\n\n 
     ....

 node_xslt result remove also xml data: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>

**Comment by albanm** [comment] 2015-02-19 20:08
Seems like the problem is related to a simple xml parsing error, not to something specific to node-libxslt.

Can you try to just parse your XML input:  'libxslt.libxmljs.parseXml(metadata);' ?

If it triggers the same error, you should simply have a closer look at your xml using an online validator or any other tool. If not please let me know.

Something else that I recommend when dealing with this sort of problem is to try using xsltproc, a simple command line tool that uses libxslt. If xsltproc works but not node-libxslt, then the problem is indeed with the node wrapper, if both fail then the problem is not specific to node-libxslt.

**Comment by kildem** [comment] 2015-02-19 20:29
what I'm trying to do is to have the same result that I have when using node_xslt (using node v <=10) with this code:

            var xslt = require('node_xslt');
            var stylesheet = xslt.readXsltString(transformXslt);
            var document = xslt.readXmlString(metadata);
            var paramArray = [
                'SerivceUri', "'" + cnf.SerivceUri + "'",
                'EntityBaseClass', "'" + cnf.EntityBaseClass + "'",
                'ContextBaseClass', "'" + cnf.ContextBaseClass + "'",
                'AutoCreateContext', "'" + cnf.AutoCreateContext + "'",
                'ContextInstanceName', "'" + cnf.ContextInstanceName + "'",
                'EntitySetBaseClass', "'" + cnf.EntitySetBaseClass + "'",
                'CollectionBaseClass', "'" + cnf.CollectionBaseClass + "'",
                'DefaultNamespace', "'" + cnf.DefaultNamespace + "'",
                'MaxDataserviceVersion', "'" + (versionInfo.maxVersion || '3.0') + "'",
                'AllowedTypesList', "'" + cnf.typeFilter + "'",
                'GenerateNavigationProperties', "'" + cnf.navigation + "'"
            ];
            var result = xslt.transform(stylesheet, document, paramArray);
            return result;

if I parse result = libxslt.libxmljs.parseXml(metadata);
result -> {}
and I receive this error: 

    { [Not found: No context found in service]
      name: 'Not found',
      message: 'No context found in service',
     .......

**Comment by albanm** [comment] 2015-02-20 20:30
Ok so clearly the problem is before even running any code of node-libxslt, it is a problem detected by libxmljs when parsing the XML input document. Have you checked the validity of this document using some other tool as I suggested ?

For example: http://www.xmlvalidation.com/

**Comment by kildem** [comment] 2015-02-21 07:36
I validate the metadata file and the answer is:
"No errors were found"

**Comment by kildem** [comment] 2015-02-21 10:47
I think there's some problem with libxmljs http://stackoverflow.com/a/27498655

**Comment by albanm** [comment] 2015-06-22 20:17
I close this as it is probably not an issue for node-libxslt.

**Closed by albanm** 2015-06-22 20:17 UTC
